#!/bin/bash

WEBHOOK_URL="https://hooks.slack.com/services/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"
MESSAGE="Your task is done @Axo solaman"

for i in 1 2 3 4 5 6 7 8 9 10; do
  curl -s -X POST -H 'Content-type: application/json' \
    --data "{\"text\":\"$MESSAGE\"}" "$WEBHOOK_URL"
  sleep 2
done
