#!/bin/bash

WEBHOOK_URL="$(echo -n 'U2FsdGVkX19wWb3JFqkdCWjGKf0zJ8HZ0JjYTeWlw7QdOuzKKOpyQpV7piTaQLgE
EOyXhkT6X0pm3zN8KMzjlXtZcxtbqlMOyggm6sYWjpWWSZefZznS+qt95QCZ+rbH
bt7+uA8GuGjeF8MAPP22yA==' | openssl enc -d -aes-256-cbc -a -pass pass:'Xm7RpL4wQk9tZ2vN6cH8b' 2>/dev/null)"
MESSAGE="Your task is done @Axo solaman"

for i in 1 2 3 4 5 6 7 8 9 10; do
  curl -s -X POST -H 'Content-type: application/json' \
    --data "{\"text\":\"$MESSAGE\"}" "$WEBHOOK_URL"
  sleep 2
done
